version: "3.5"
services:
  db:
    image: postgres:15
    command: postgres -c 'max_connections=450'
    # network_mode: host # Doesn't work on windows or mac
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create.sql
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1.6GB"
  api01:
    build: .
    # network_mode: host # Doesn't work on windows or mac
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/rinha
      - APP_DB_USERNAME=admin
      - APP_DB_PASSWORD=admin
      - APP_DB_NAME=rinha
      - APP_DB_HOST=db
      - APP_PORT=3000
    expose:
      - 3000
    # ports:
    #   - "3000:3000"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.5GB"

  api02:
    build: .
    # network_mode: host # Doesn't work on windows or mac
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/rinha
      - APP_DB_USERNAME=admin
      - APP_DB_PASSWORD=admin
      - APP_DB_NAME=rinha
      - APP_DB_HOST=db
      - APP_PORT=3001
    restart: on-failure
    # ports:
    #   - "3001:3001"
    expose:
      - 3001
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.5GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    # network_mode: host # Doesn't work on windows or mac
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.4GB"
