CREATE EXTENSION IF NOT EXISTS pg_trgm;  

CREATE TABLE IF NOT EXISTS PERSON (
  ID UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
  NICKNAME TEXT NOT NULL UNIQUE,
  NAME     TEXT NOT NULL,
  BIRTHDAY DATE NOT NULL, 
  STACK    TEXT,
  SEARCH   TEXT GENERATED ALWAYS AS (
    lower(NICKNAME || ' ' || name || ' ' || STACK)
  ) STORED
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_SERCH_TGRM ON PERSON USING GIST (SEARCH GIST_TRGM_OPS);
